### ISSUE TITLE
(Firefox) Campos de texto no seleccionables

### ISSUE THREAD

**Issue by titanioverde** [Kurobyte/ac-hhd#1]
Mediante la última versión estable de Firefox, en los campos de texto de las ventanas de export y share no se puede seleccionar nada. Ni arrastrando el botón izquierdo del ratón, ni con doble clic.
Si elijo Seleccionar todo en el menú contextual, marca toda la página, excepto dicho campo.
De esta manera solo puedo compartir copiando manualmente el enlace. (Viva is.gd)

En una versión no muy reciente de Chromium sí que se deja.

**Comment by titanioverde** [comment]
Veo que ya se puede seleccionar texto arrastrando. Con doble clic solo coge parte de la cadena (a saber si es el navegador o el SO).
Debe de haber alguna manera de copiar al portapapeles, o bien dejar marcado todo ese campo, con un clic desde Javascript.

**Comment by Kurobyte** [comment]
Con el ultimo commit debería solucionarse.
Se ha añadido que autoseleccione el texto y lo copie el portapapeles al hacer clic en el recuadro de exportar.

**Comment by titanioverde** [comment]
Efectivamente, ahora al hacer un simple clic se selecciona todo el campo y se copia al portapapeles.
¡Bien hecho, camarada! :-D Ya puedes descansar.
